# Do NOT update manually; changes here will be overwritten by Copier
_commit: 81cc7fe
_src_path: https://github.com/openg2p/openg2p-fastapi-template
github_ci_docker_build: true
github_ci_openapi_publish: true
github_ci_precommit: true
github_ci_pypi_publish: true
github_ci_tests: true
github_ci_tests_codecov: true
module_name: g2p_cash_transfer_bridge
org_name: OpenG2P
org_slug: OpenG2P
package_name: g2p-cash-transfer-bridge
repo_name: G2P Cash Transfer Bridge
repo_slug: g2p-cash-transfer-bridge

