name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution g2p-cash-transfer-bridge-core
      run: python -m build ./g2p-cash-transfer-bridge-core
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: g2p-cash-transfer-bridge-core/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution g2p-cash-transfer-bridge-api
      run: python -m build ./g2p-cash-transfer-bridge-api
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: g2p-cash-transfer-bridge-api/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution gctb-translate-id-fa
      run: python -m build ./gctb-translate-id-fa
    - name: Publish gctb-translate-id-fa
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: gctb-translate-id-fa/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
